BrokerSpreadUrls:
  Vantage: https://www.myfxbook.com/forex-broker-quotes/vantage/6052
  Pepperstone: https://www.myfxbook.com/forex-broker-quotes/pepperstone/1589
  FusionMarkets: https://www.myfxbook.com/forex-broker-quotes/fusion-markets/6211
  UltimaMarkets: https://www.myfxbook.com/forex-broker-quotes/ultima-markets/15447
  Tickmill: https://www.myfxbook.com/forex-broker-quotes/tickmill/2512
  Errante: https://www.myfxbook.com/forex-broker-quotes/errante/11720
  CapitalCom: https://www.myfxbook.com/forex-broker-quotes/capitalcom/12345
  XmGroup: https://www.myfxbook.com/forex-broker-quotes/xm-group/2824
  Headway: https://www.myfxbook.com/forex-broker-quotes/headway/15478
  ZeroMarkets: https://www.myfxbook.com/forex-broker-quotes/zero-markets/10281
  AcySecurities: https://www.myfxbook.com/forex-broker-quotes/acy-securities/5909
  MonetaMarkets: https://www.myfxbook.com/forex-broker-quotes/moneta-markets/12667
  BlueberryMarkets: https://www.myfxbook.com/forex-broker-quotes/blueberry-markets/3767
  EbcFinancialGroup: https://www.myfxbook.com/forex-broker-quotes/ebc-financial-group/13328
  FpMarkets: https://www.myfxbook.com/forex-broker-quotes/fp-markets/1420
  Fbs: https://www.myfxbook.com/forex-broker-quotes/fbs/187
  DnaMarkets: https://www.myfxbook.com/forex-broker-quotes/dna-markets/15374
  OqTime: https://www.myfxbook.com/forex-broker-quotes/oqtima/15559
  ExclusiveMarkets: https://www.myfxbook.com/forex-broker-quotes/exclusive-markets/10018
  GoMarkets: https://www.myfxbook.com/forex-broker-quotes/go-markets/169
  FxPro: https://www.myfxbook.com/forex-broker-quotes/fxpro/5168
  ActivTrades: https://www.myfxbook.com/forex-broker-quotes/activtrades/15732
  Octa: https://www.myfxbook.com/forex-broker-quotes/octa/1124
  ForexCom: https://www.myfxbook.com/forex-broker-quotes/forexcom/6245
  AccentForex: https://www.myfxbook.com/forex-broker-quotes/accentforex/727
  Fxtm: https://www.myfxbook.com/forex-broker-quotes/fxtm/3228
  RoboForex: https://www.myfxbook.com/forex-broker-quotes/roboforex/4552
  MultiBankGroup: https://www.myfxbook.com/forex-broker-quotes/multibank-group/14635
  LiteForex: https://www.myfxbook.com/forex-broker-quotes/liteforex/116
  Just2Trade: https://www.myfxbook.com/forex-broker-quotes/just2trade/3278
  CmcMarkets: https://www.myfxbook.com/forex-broker-quotes/cmc-markets/5569
  Alpari: https://www.myfxbook.com/forex-broker-quotes/alpari-comoros-ltd/2768
  Fxgt: https://www.myfxbook.com/forex-broker-quotes/fxgt/15355
  Exness: https://www.myfxbook.com/forex-broker-quotes/exness/5870
  JustMarkets: https://www.myfxbook.com/forex-broker-quotes/justmarkets/12920
  FxPig: https://www.myfxbook.com/forex-broker-quotes/fxpig/757
  XmTrading: https://www.myfxbook.com/forex-broker-quotes/xmtrading/13283
  StarTrader: https://www.myfxbook.com/forex-broker-quotes/startrader/15089
  Tmgm: https://www.myfxbook.com/forex-broker-quotes/tmgm/12872
  EightCap: https://www.myfxbook.com/forex-broker-quotes/eightcap/2929
  IcMarkets: https://www.myfxbook.com/forex-broker-quotes/ic-markets/2320
  Afterprime: https://www.myfxbook.com/forex-broker-quotes/afterprime/15267